// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHouse.Models;

namespace StudentHouse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentHouse.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CookEmail");

                    b.Property<string>("CookName");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("MaxGuests");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<int?>("StudentId");

                    b.HasKey("MealId");

                    b.HasIndex("StudentId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("StudentHouse.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentHouse.Models.StudentMeal", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("MealId");

                    b.HasKey("StudentId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("StudentMeal");
                });

            modelBuilder.Entity("StudentHouse.Models.Meal", b =>
                {
                    b.HasOne("StudentHouse.Models.Student")
                        .WithMany("MealsCooked")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("StudentHouse.Models.StudentMeal", b =>
                {
                    b.HasOne("StudentHouse.Models.Meal", "Meal")
                        .WithMany("Guests")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentHouse.Models.Student", "Student")
                        .WithMany("MealsAttend")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
